<?php

namespace App\Http\Requests\Admin\RealEstate;

use Illuminate\Foundation\Http\FormRequest;

class RealEstateUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            "building_type_id" => "required|numeric|in:1,2,3,4,5,6,7,8,9",
            "building_type_use_id" => "required|numeric|in:1,2",
            "national_address" => "required|string",
            "lat" => "required|numeric",
            "lon" => "required|numeric",
            "number_floors" => "numeric|nullable",
            "number_units" => "numeric|nullable",
            "number_parking_lots" => "numeric|nullable",
            "units" => "required|array|min:1",
            "units.*.id" => "required|numeric",
            "units.*.purpose_property_id" => "required|numeric|in:1,2",
            "units.*.price" => "required|numeric",
            "units.*.unit_type" => "required|string",
            "units.*.unit_number" => "required|string",
            "units.*.floor_number" => "numeric|nullable",
            "units.*.unit_area" => "required|numeric",
            "units.*.furnished" => "string|nullable",
            "units.*.composite_kitchen_cabinets" => "boolean|nullable",
            "units.*.ac_type" => "string|nullable",
            "units.*.num_ac_units" => "numeric|nullable",
            "units.*.electricity_meter_number" => "numeric|nullable",
            "units.*.electricity_meter_reading" => "numeric|nullable",
            "units.*.gas_meter_number" => "numeric|nullable",
            "units.*.gas_meter_reading" => "numeric|nullable",
            "units.*.water_meter_number" => "numeric|nullable",
            "units.*.water_meter_reading" => "numeric|nullable",
            "units.*.description" => "string|nullable",
            "units.*.is_publish" => "required|boolean|nullable",
            "units.*.unit_length" => "numeric|nullable",
            "units.*.unit_direction" => "string|nullable",
            "units.*.number_parking_lots" => "numeric|nullable",
            "units.*.sign_area" => "numeric|nullable",
            "units.*.sign_location" => "string|nullable",
            "units.*.special_sign_specification" => "string|nullable",
            "units.*.insurance_policy_number" => "numeric|nullable",
            "units.*.mezzanine" => "boolean|nullable",
            "units.*.unit_finishing" => "boolean|nullable",


            "new_units" => "array|min:1",
            "new_units.*.purpose_property_id" => "required|numeric|in:1,2",
            "new_units.*.price" => "required|numeric",
            "new_units.*.unit_type" => "required|string",
            "new_units.*.unit_number" => "required|string",
            "new_units.*.floor_number" => "numeric|nullable",
            "new_units.*.unit_area" => "required|numeric",
            "new_units.*.furnished" => "string|nullable",
            "new_units.*.composite_kitchen_cabinets" => "boolean|nullable",
            "new_units.*.ac_type" => "string|nullable",
            "new_units.*.num_ac_units" => "numeric|nullable",
            "new_units.*.electricity_meter_number" => "numeric|nullable",
            "new_units.*.electricity_meter_reading" => "numeric|nullable",
            "new_units.*.gas_meter_number" => "numeric|nullable",
            "new_units.*.gas_meter_reading" => "numeric|nullable",
            "new_units.*.water_meter_number" => "numeric|nullable",
            "new_units.*.water_meter_reading" => "numeric|nullable",
            "new_units.*.description" => "string|nullable",
            "new_units.*.is_publish" => "required|boolean|nullable",
            "new_units.*.media" => "required|array|min:1",
            "new_units.*.media.*" => "max:2048",
            "new_units.*.unit_length" => "numeric|nullable",
            "new_units.*.unit_direction" => "string|nullable",
            "new_units.*.number_parking_lots" => "numeric|nullable",
            "new_units.*.sign_area" => "numeric|nullable",
            "new_units.*.sign_location" => "string|nullable",
            "new_units.*.special_sign_specification" => "string|nullable",
            "new_units.*.insurance_policy_number" => "numeric|nullable",
            "new_units.*.mezzanine" => "boolean|nullable",
            "new_units.*.unit_finishing" => "boolean|nullable",
        ];
    }

    public function messages()
    {
        return [
            "building_type_id.required" => __("real_estate.you must choose building type"),
            "building_type_id.numeric" => __("real_estate.you must choose building type and send id number"),
            "building_type_id.in" => __("real_estate.you must choose building type from 1 : 9"),
            "building_type_use_id.required" => __("real_estate.you must choose building type use"),
            "building_type_use_id.numeric" => __("real_estate.you must choose building type use and send id number"),
            "building_type_use_id.in" => __("real_estate.you must choose building type from 1 : 2"),
            "national_address.required" => __("real_estate.you must enter national address"),
            "national_address.string" => __("real_estate.you must enter national address as string"),
            "lat.required" => __("real_estate.you must enter lat"),
            "lat.numeric" => __("real_estate.you must enter lat as number"),
            "lon.required" => __("real_estate.you must enter lon"),
            "lon.numeric" => __("real_estate.you must enter lon as number"),
            "number_floors.numeric" => __("real_estate.you must enter number floors as number"),
            "number_units.numeric" => __("real_estate.you must enter number units as number"),
            "number_parking_lots.numeric" => __("real_estate.you must enter number parking lots as number"),
            "cover_real_estate.required" => __("real_estate.you must choose cover image"),
            "cover_real_estate.mimes" => __("real_estate.you must choose cover image as jpg,png,jpeg"),
            "units.required" => __("real_estate.you must add unit"),
            "units.array" => __("real_estate.you must add unit as array"),
            "units.min" => __("real_estate.you must add min 1 unit"),
            "units.*.id.required" => __("real_estate.you must send unit id"),
            "units.*.id.numeric" => __("real_estate.you must send unit id as number"),
            "units.*.purpose_property_id.required" => __("real_estate.you must choose purpose property"),
            "units.*.purpose_property_id.numeric" => __("real_estate.you must choose purpose property and send id number"),
            "units.*.price.required" => __("real_estate.you must enter price"),
            "units.*.price.numeric" => __("real_estate.you must enter price as number"),
            "units.*.unit_type.required" => __("real_estate.you must enter unit type"),
            "units.*.unit_type.string" => __("real_estate.you must enter unit type as string"),
            "units.*.unit_number.required" => __("real_estate.you must enter unit number"),
            "units.*.unit_number.string" => __("real_estate.you must enter unit number as string"),
            "units.*.floor_number.numeric" => __("real_estate.you must enter floor number as number"),
            "units.*.unit_area.required" => __("real_estate.you must enter unit area"),
            "units.*.unit_area.numeric" => __("real_estate.you must enter unit area as number"),
            "units.*.furnished.string" => __("real_estate.you must enter furnished as string"),
            "units.*.composite_kitchen_cabinets.boolean" => __("real_estate.you must enter furnished as boolean 1 or 0"),
            "units.*.ac_type.string" => __("real_estate.you must enter ac_type as string"),
            "units.*.num_ac_units.numeric" => __("real_estate.you must enter num_ac_units as numeric"),
            "units.*.electricity_meter_number.numeric" => __("real_estate.you must enter electricity meter number as numeric"),
            "units.*.electricity_meter_reading.numeric" => __("real_estate.you must enter electricity meter reading as numeric"),
            "units.*.gas_meter_number.numeric" => __("real_estate.you must enter gas meter number as numeric"),
            "units.*.gas_meter_reading.numeric" => __("real_estate.you must enter gas meter reading as numeric"),
            "units.*.water_meter_number.numeric" => __("real_estate.you must enter water meter number as numeric"),
            "units.*.water_meter_reading.numeric" => __("real_estate.you must enter water meter reading as numeric"),
            "units.*.description.string" => __("real_estate.you must enter description as string"),
            "units.*.is_publish.required" => __("real_estate.you must choose is_publish"),
            "units.*.description.boolean" => __("real_estate.you must choose is_publish as yes or no"),
            "units.*.media.required" => __("real_estate.you must choose unit media"),
            "units.*.media.array" => __("real_estate.you must choose unit media as array"),
            "units.*.unit_length.numeric" => __("real_estate.you must enter unit length as number"),
            "units.*.unit_direction.string" => __("real_estate.you must enter unit direction as string"),
            "units.*.number_parking_lots.numeric" => __("real_estate.you must enter number parking lots as number"),
            "units.*.sign_area.numeric" => __("real_estate.you must enter sign area as number"),
            "units.*.sign_location.string" => __("real_estate.you must enter sign location as string"),
            "units.*.special_sign_specification.string" => __("real_estate.you must enter special sign specification as string"),
            "units.*.insurance_policy_number.numeric" => __("real_estate.you must enter insurance policy number as number"),
            "units.*.mezzanine.boolean" => __("real_estate.you must enter mezzanine as boolean yes or no"),
            "units.*.unit_finishing.boolean" => __("real_estate.you must enter unit finishing as boolean yes or no"),


            "new_units.array" => __("real_estate.you must add unit as array"),
            "new_units.min" => __("real_estate.you must add min 1 unit"),
            "new_units.*.purpose_property_id.required" => __("real_estate.you must choose purpose property"),
            "new_units.*.purpose_property_id.numeric" => __("real_estate.you must choose purpose property and send id number"),
            "new_units.*.price.required" => __("real_estate.you must enter price"),
            "new_units.*.price.numeric" => __("real_estate.you must enter price as number"),
            "new_units.*.unit_type.required" => __("real_estate.you must enter unit type"),
            "new_units.*.unit_type.string" => __("real_estate.you must enter unit type as string"),
            "new_units.*.unit_number.required" => __("real_estate.you must enter unit number"),
            "new_units.*.unit_number.string" => __("real_estate.you must enter unit number as string"),
            "new_units.*.floor_number.numeric" => __("real_estate.you must enter floor number as number"),
            "new_units.*.unit_area.required" => __("real_estate.you must enter unit area"),
            "new_units.*.unit_area.numeric" => __("real_estate.you must enter unit area as number"),
            "new_units.*.furnished.string" => __("real_estate.you must enter furnished as string"),
            "new_units.*.composite_kitchen_cabinets.boolean" => __("real_estate.you must enter furnished as boolean 1 or 0"),
            "new_units.*.ac_type.string" => __("real_estate.you must enter ac_type as string"),
            "new_units.*.num_ac_units.numeric" => __("real_estate.you must enter num_ac_units as numeric"),
            "new_units.*.electricity_meter_number.numeric" => __("real_estate.you must enter electricity meter number as numeric"),
            "new_units.*.electricity_meter_reading.numeric" => __("real_estate.you must enter electricity meter reading as numeric"),
            "new_units.*.gas_meter_number.numeric" => __("real_estate.you must enter gas meter number as numeric"),
            "new_units.*.gas_meter_reading.numeric" => __("real_estate.you must enter gas meter reading as numeric"),
            "new_units.*.water_meter_number.numeric" => __("real_estate.you must enter water meter number as numeric"),
            "new_units.*.water_meter_reading.numeric" => __("real_estate.you must enter water meter reading as numeric"),
            "new_units.*.description.string" => __("real_estate.you must enter description as string"),
            "new_units.*.is_publish.required" => __("real_estate.you must choose is_publish"),
            "new_units.*.description.boolean" => __("real_estate.you must choose is_publish as yes or no"),
            "new_units.*.media.required" => __("real_estate.you must choose unit media"),
            "new_units.*.media.array" => __("real_estate.you must choose unit media as array"),
            "new_units.*.unit_length.numeric" => __("real_estate.you must enter unit length as number"),
            "new_units.*.unit_direction.string" => __("real_estate.you must enter unit direction as string"),
            "new_units.*.number_parking_lots.numeric" => __("real_estate.you must enter number parking lots as number"),
            "new_units.*.sign_area.numeric" => __("real_estate.you must enter sign area as number"),
            "new_units.*.sign_location.string" => __("real_estate.you must enter sign location as string"),
            "new_units.*.special_sign_specification.string" => __("real_estate.you must enter special sign specification as string"),
            "new_units.*.insurance_policy_number.numeric" => __("real_estate.you must enter insurance policy number as number"),
            "new_units.*.mezzanine.boolean" => __("real_estate.you must enter mezzanine as boolean yes or no"),
            "new_units.*.unit_finishing.boolean" => __("real_estate.you must enter unit finishing as boolean yes or no"),
        ];
    }
}
